<?php

namespace src\Opendelivery\Enums;

abstract class DeliveryStatus
{
    const PENDING = 'PENDING';
    const UNATTENDED = 'UNATTENDED';
    const NOT_CALLED = 'NOT_CALLED';
    const REJECTED = 'REJECTED';
    const CANCELLED = 'CANCELLED';
    const ACCEPTED = 'ACCEPTED';
    const PICKUP_ONGOING = 'PICKUP_ONGOING';
    const ARRIVED_AT_MERCHANT = 'ARRIVED_AT_MERCHANT';
    const ORDER_PICKED = 'ORDER_PICKED';
    const DELIVERY_ONGOING = 'DELIVERY_ONGOING';
    const ARRIVED_AT_CUSTOMER = 'ARRIVED_AT_CUSTOMER';
    const ORDER_DELIVERED = 'ORDER_DELIVERED';
    const RETURNING_TO_MERCHANT = 'RETURNING_TO_MERCHANT';
    const RETURNED_TO_MERCHANT = 'RETURNED_TO_MERCHANT';
    const DELIVERY_FINISHED = 'DELIVERY_FINISHED';
}