<?php

namespace src\Delivery\Enums;

abstract class EventWebhookType
{
    const DELIVERY_DIRETO_APPROVED = 'DELIVERY_DIRETO_APPROVED';
    const DELIVERY_DIRETO_HIDDEN = 'DELIVERY_DIRETO_HIDDEN';
    const DELIVERY_DIRETO_IN_TRANSIT = 'DELIVERY_DIRETO_IN_TRANSIT';
    const DELIVERY_DIRETO_REJECTED = 'DELIVERY_DIRETO_REJECTED';
    const DELIVERY_DIRETO_DONE = 'DELIVERY_DIRETO_DONE';

    const MACHINE_DELIVERY_IN_TRANSIT = 'MACHINE_DELIVERY_IN_TRANSIT';
    const MACHINE_DELIVERY_FINISHED = 'MACHINE_DELIVERY_FINISHED';
    const MACHINE_ASSIGN_DRIVER = 'MACHINE_ASSIGN_DRIVER';
    const MACHINE_GOING_TO_ORIGIN = 'MACHINE_GOING_TO_ORIGIN';
    const MACHINE_ARRIVED_AT_ORIGIN = 'MACHINE_ARRIVED_AT_ORIGIN';
    const MACHINE_DISPATCHED = 'MACHINE_DISPATCHED';
    const MACHINE_ARRIVED_AT_DESTINATION = 'MACHINE_ARRIVED_AT_DESTINATION';
    const MACHINE_INSERT_ENTITY = 'MACHINE_INSERT_ENTITY';
    const MACHINE_UPDATE_ENTITY = 'MACHINE_UPDATE_ENTITY';
    const MACHINE_DELETE_ENTITY = 'MACHINE_DELETE_ENTITY';
    const MACHINE_BATCH_INSERT_ENTITY = 'MACHINE_BATCH_INSERT_ENTITY';
    const MACHINE_SEND_OPENDELIVERY_EVENT = 'MACHINE_SEND_OPENDELIVERY_EVENT';

    const ANOTAAI_CREATED = 'ANOTAAI_CREATED';
    const ANOTAAI_CANCELED = 'ANOTAAI_CANCELED';

    const NEEMO_CREATED = 'NEEMO_CREATED';

    const AIQFOME_READ_ORDER = 'AIQFOME_READ-ORDER';
    const AIQFOME_READY_ORDER = 'AIQFOME_READY-ORDER';
    const AIQFOME_CANCEL_ORDER = 'AIQFOME_CANCEL-ORDER';

    const IFOOD_CONFIRMED = 'IFOOD_CONFIRMED';
    const IFOOD_DISPATCHED = 'IFOOD_DISPATCHED';
    const IFOOD_CANCELLED = 'IFOOD_CANCELLED';
    const IFOOD_CONCLUDED = 'IFOOD_CONCLUDED';
    const IFOOD_OTHER = 'IFOOD_OTHER';
    const IFOOD_KEEPALIVE = 'IFOOD_KEEPALIVE';
}