name: Unit Tests

on: ['pull_request']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Cache Composer dependencies (www)
        uses: actions/cache@v4
        with:
          path: www/vendor
          key: composer-www-cache-${{ runner.os }}-${{ hashFiles('www/composer.lock') }}
          restore-keys: |
            composer-www-cache-${{ runner.os }}-

      - name: Install Dependencies (www)
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        working-directory: www

      - name: Cache Composer dependencies (www/src)
        uses: actions/cache@v4
        with:
          path: www/src/vendor
          key: composer-src-cache-${{ runner.os }}-${{ hashFiles('www/src/composer.lock') }}
          restore-keys: |
            composer-src-cache-${{ runner.os }}-

      - name: Install Dependencies (www/src)
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        working-directory: www/src

      - name: Run Tests
        run: ./vendor/bin/pest --coverage --min=50
        working-directory: www
